// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqgbybbynzorzkktgcxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZ2J5YmJ5bnpvcnpra3RnY3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzQyMDUsImV4cCI6MjA3MjUxMDIwNX0.KVa-wjjMB1bVlmKoo4DSVvu0Z_r36KcBXuCFcjpcxo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});